-- PostgreSQL schema baseline for the SCMS relational model.
-- Source business schema: repository-root databaseschema.sql (SQL Server).
-- Keep this provider-specific migration aligned with the entities and preserve
-- business constraints through the PostgreSQL trigger migration V2.

-- MODULE A: ĐỊNH DANH & PHÂN QUYỀN
-- =====================================================================

CREATE TABLE roles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(50)  NOT NULL UNIQUE,
    name            VARCHAR(100) NOT NULL,
    description     VARCHAR(255) NULL,
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE permissions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(100) NOT NULL UNIQUE,
    name            VARCHAR(150) NOT NULL,
    module          VARCHAR(50)  NOT NULL,
    created_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE role_permissions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id         BIGINT NOT NULL,
    permission_id   BIGINT NOT NULL,
    CONSTRAINT uq_role_permission UNIQUE (role_id, permission_id),
    CONSTRAINT fk_rp_role       FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT fk_rp_permission FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id         BIGINT NOT NULL,
    full_name       VARCHAR(150) NOT NULL,
    email           VARCHAR(150) NOT NULL UNIQUE,
    phone           VARCHAR(20)  NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    dob             DATE NULL,
    gender          VARCHAR(10) NULL
                    CONSTRAINT ck_users_gender CHECK (gender IN ('male','female','other')),
    avatar_url      VARCHAR(255) NULL,
    address         VARCHAR(255) NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'active'
                    CONSTRAINT ck_users_status CHECK (status IN ('active','inactive','locked')),
    last_login_at   TIMESTAMP NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP NULL,
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

CREATE INDEX ix_users_role ON users (role_id);

CREATE TABLE members (
    user_id                     BIGINT PRIMARY KEY,
    membership_code             VARCHAR(30) NOT NULL UNIQUE,
    join_date                   DATE NOT NULL,
    health_notes                TEXT NULL,
    fitness_goal                VARCHAR(255) NULL,
    fitness_level               VARCHAR(20) NOT NULL DEFAULT 'beginner'
                                CONSTRAINT ck_members_level CHECK (fitness_level IN ('beginner','intermediate','advanced')),
    emergency_contact_name      VARCHAR(150) NULL,
    emergency_contact_phone     VARCHAR(20) NULL,
    CONSTRAINT fk_members_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE coaches (
    user_id             BIGINT PRIMARY KEY,
    specialization      VARCHAR(150) NULL,
    bio                 TEXT NULL,
    certification       VARCHAR(255) NULL,
    hire_date           DATE NULL,
    employment_status   VARCHAR(20) NOT NULL DEFAULT 'active'
                        CONSTRAINT ck_coaches_status CHECK (employment_status IN ('active','on_leave','terminated')),
    CONSTRAINT fk_coaches_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE receptionists (
    user_id             BIGINT PRIMARY KEY,
    hire_date           DATE NULL,
    shift               VARCHAR(50) NULL,
    employment_status   VARCHAR(20) NOT NULL DEFAULT 'active'
                        CONSTRAINT ck_receptionists_status CHECK (employment_status IN ('active','on_leave','terminated')),
    CONSTRAINT fk_receptionists_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE center_managers (
    user_id     BIGINT PRIMARY KEY,
    hire_date   DATE NULL,
    CONSTRAINT fk_center_managers_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- =====================================================================
-- MODULE B: DANH MỤC / CƠ SỞ VẬT CHẤT
-- =====================================================================

CREATE TABLE disciplines (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL UNIQUE,
    description     TEXT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rooms (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    location    VARCHAR(150) NULL,
    capacity    INT NOT NULL,
    status      VARCHAR(20) NOT NULL DEFAULT 'available'
               CONSTRAINT ck_rooms_status CHECK (status IN ('available','maintenance','closed'))
);

CREATE TABLE membership_packages (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                 VARCHAR(150) NOT NULL,
    description          TEXT NULL,
    price                DECIMAL(12,2) NOT NULL,
    duration_days        INT NOT NULL,
    class_credit_limit   INT NULL,
    status               VARCHAR(20) NOT NULL DEFAULT 'active'
                        CONSTRAINT ck_packages_status CHECK (status IN ('active','inactive')),
    created_by           BIGINT NULL,
    created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_packages_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

-- =====================================================================
-- MODULE C: GÓI THÀNH VIÊN
-- =====================================================================

CREATE TABLE membership_subscriptions (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id                   BIGINT NOT NULL,
    package_id                  BIGINT NOT NULL,
    previous_subscription_id    BIGINT NULL,
    start_date                  DATE NOT NULL,
    end_date                    DATE NOT NULL,
    status                      VARCHAR(20) NOT NULL DEFAULT 'pending_payment'
                                CONSTRAINT ck_subscriptions_status CHECK (status IN ('pending_payment','active','expired','cancelled')),
    qr_code                     VARCHAR(255) NULL UNIQUE,
    created_by                  BIGINT NULL,
    created_at                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sub_member    FOREIGN KEY (member_id) REFERENCES members(user_id),
    CONSTRAINT fk_sub_package   FOREIGN KEY (package_id) REFERENCES membership_packages(id),
    CONSTRAINT fk_sub_previous  FOREIGN KEY (previous_subscription_id) REFERENCES membership_subscriptions(id),
    CONSTRAINT fk_sub_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE INDEX ix_subscriptions_member_status ON membership_subscriptions (member_id, status);
CREATE INDEX ix_subscriptions_end_date ON membership_subscriptions (end_date);

-- =====================================================================
-- MODULE D: LỚP HỌC & LỊCH
-- =====================================================================

CREATE TABLE classes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(150) NOT NULL,
    discipline_id   BIGINT NOT NULL,
    coach_id        BIGINT NOT NULL,
    room_id         BIGINT NOT NULL,
    capacity        INT NOT NULL,
    level           VARCHAR(20) NOT NULL DEFAULT 'all'
                   CONSTRAINT ck_classes_level CHECK (level IN ('beginner','intermediate','advanced','all')),
    description     TEXT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'active'
                   CONSTRAINT ck_classes_status CHECK (status IN ('active','inactive','archived')),
    created_by      BIGINT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_classes_discipline FOREIGN KEY (discipline_id) REFERENCES disciplines(id),
    CONSTRAINT fk_classes_coach      FOREIGN KEY (coach_id) REFERENCES coaches(user_id),
    CONSTRAINT fk_classes_room       FOREIGN KEY (room_id) REFERENCES rooms(id),
    CONSTRAINT fk_classes_created_by FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE INDEX ix_classes_coach ON classes (coach_id);

CREATE TABLE class_sessions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id        BIGINT NOT NULL,
    session_date    DATE NOT NULL,
    start_time      TIME NOT NULL,
    end_time        TIME NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'scheduled'
                   CONSTRAINT ck_sessions_status CHECK (status IN ('scheduled','completed','cancelled')),
    cancel_reason   VARCHAR(255) NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sessions_class FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE
);

CREATE INDEX ix_sessions_class_date ON class_sessions (class_id, session_date);

CREATE TABLE class_enrollments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id        BIGINT NOT NULL,
    member_id       BIGINT NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'booked'
                   CONSTRAINT ck_enrollments_status CHECK (status IN ('booked','cancelled','completed')),
    enrolled_at     TIMESTAMP NOT NULL,
    cancelled_at    TIMESTAMP NULL,
    cancelled_by    BIGINT NULL,
    cancel_reason   VARCHAR(255) NULL,
    CONSTRAINT fk_enrollments_class  FOREIGN KEY (class_id) REFERENCES classes(id),
    CONSTRAINT fk_enrollments_member FOREIGN KEY (member_id) REFERENCES members(user_id),
    CONSTRAINT fk_enrollments_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES users(id)
);

CREATE INDEX ix_enrollments_member_status ON class_enrollments (member_id, status);
CREATE INDEX ix_enrollments_class_status ON class_enrollments (class_id, status);

-- [P1 — Booking history] Bỏ UNIQUE(class_id, member_id) cứng vì nó chặn luôn việc member
-- đăng ký lại một lớp đã từng hủy trước đó (mất khả năng lưu lịch sử booking).
-- Thay bằng filtered unique index: chỉ đảm bảo KHÔNG có 2 dòng 'booked' cùng lúc cho 1 cặp
-- (class_id, member_id); các dòng 'cancelled'/'completed' cũ vẫn giữ nguyên làm lịch sử.
CREATE UNIQUE INDEX uq_enrollment_active
ON class_enrollments (class_id, member_id)
WHERE status = 'booked';

CREATE TABLE class_waitlists (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id        BIGINT NOT NULL,
    member_id       BIGINT NOT NULL,
    requested_at    TIMESTAMP NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'waiting'
                   CONSTRAINT ck_waitlist_status CHECK (status IN ('waiting','notified','expired')),
    CONSTRAINT fk_waitlist_class  FOREIGN KEY (class_id) REFERENCES classes(id),
    CONSTRAINT fk_waitlist_member FOREIGN KEY (member_id) REFERENCES members(user_id)
);

-- [FIX 1NF-3NF §3.4] Ngăn 1 member bị chèn trùng nhiều dòng "đang chờ" cho cùng 1 lớp.
-- Dùng UNIQUE INDEX có điều kiện (filtered index) vì SQL Server hỗ trợ WHERE trên UNIQUE INDEX.
-- Sau khi status chuyển sang 'notified'/'expired', member có thể được thêm lại vào waitlist (dòng mới).
CREATE UNIQUE INDEX uq_waitlist_active
ON class_waitlists (class_id, member_id)
WHERE status = 'waiting';

-- =====================================================================
-- MODULE E: CHECK-IN & ĐIỂM DANH
-- =====================================================================

CREATE TABLE center_checkins (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id       BIGINT NOT NULL,
    check_in_time   TIMESTAMP NOT NULL,
    check_out_time  TIMESTAMP NULL,
    method          VARCHAR(10) NOT NULL DEFAULT 'qr'
                   CONSTRAINT ck_checkins_method CHECK (method IN ('qr','manual')),
    recorded_by     BIGINT NULL,
    gate            VARCHAR(50) NULL,
    CONSTRAINT fk_checkins_member      FOREIGN KEY (member_id) REFERENCES members(user_id),
    CONSTRAINT fk_checkins_recorded_by FOREIGN KEY (recorded_by) REFERENCES users(id)
);

CREATE INDEX ix_checkins_member_time ON center_checkins (member_id, check_in_time);

CREATE TABLE session_attendance (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id      BIGINT NOT NULL,
    member_id       BIGINT NOT NULL,
    status          VARCHAR(20) NOT NULL
                   CONSTRAINT ck_attendance_status CHECK (status IN ('present','absent','late','excused')),
    checked_in_at   TIMESTAMP NULL,
    recorded_by     BIGINT NOT NULL,
    notes           VARCHAR(255) NULL,
    CONSTRAINT uq_session_member UNIQUE (session_id, member_id),
    CONSTRAINT fk_attendance_session FOREIGN KEY (session_id) REFERENCES class_sessions(id),
    CONSTRAINT fk_attendance_member  FOREIGN KEY (member_id) REFERENCES members(user_id),
    CONSTRAINT fk_attendance_coach   FOREIGN KEY (recorded_by) REFERENCES coaches(user_id)
);

CREATE INDEX ix_attendance_member ON session_attendance (member_id);

-- =====================================================================
-- RÀNG BUỘC NGHIỆP VỤ BỔ SUNG (P1–P4)
-- P1 đã xử lý ở trên (filtered unique index cho class_enrollments).
-- P2, P3, P4 xử lý bằng TRIGGER vì đây đều là kiểm tra cross-row / cross-table
-- mà CHECK CONSTRAINT thông thường của SQL Server không làm được.
-- =====================================================================

-- ---------------------------------------------------------------------
-- [P2 — Class capacity] Không cho phép số lượng booking đang active ('booked')
-- của một lớp vượt quá classes.capacity.
-- ---------------------------------------------------------------------
-- ---------------------------------------------------------------------
-- [P3 — Coach/Room schedule conflict] Không cho phép 2 buổi học (class_sessions)
-- cùng coach hoặc cùng room bị trùng/chồng lấn thời gian trong cùng một ngày.
-- Coach/Room được lấy gián tiếp qua classes (class_sessions.class_id -> classes.coach_id/room_id).
-- Điều kiện overlap chuẩn: NOT (end1 <= start2 OR start1 >= end2)
-- ---------------------------------------------------------------------
-- ---------------------------------------------------------------------
-- [P4 — Membership validation] Trước khi tạo booking (class_enrollments) hoặc
-- check-in (center_checkins), member phải có membership_subscriptions với
-- status = 'active' VÀ end_date >= ngày hiện tại (chưa hết hạn).
-- ---------------------------------------------------------------------
-- =====================================================================
-- MODULE F: THANH TOÁN & BÁO CÁO
-- =====================================================================

CREATE TABLE payments (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id               BIGINT NOT NULL,
    subscription_id         BIGINT NULL,
    class_enrollment_id     BIGINT NULL,
    amount                  DECIMAL(12,2) NOT NULL,
    method                  VARCHAR(20) NOT NULL
                           CONSTRAINT ck_payments_method CHECK (method IN ('cash','pos','bank_transfer','online_wallet')),
    status                  VARCHAR(20) NOT NULL DEFAULT 'pending'
                           CONSTRAINT ck_payments_status CHECK (status IN ('success','pending','failed','refunded')),
    paid_at                 TIMESTAMP NULL,
    received_by             BIGINT NULL,
    note                    VARCHAR(255) NULL,
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payments_member       FOREIGN KEY (member_id) REFERENCES members(user_id),
    CONSTRAINT fk_payments_subscription FOREIGN KEY (subscription_id) REFERENCES membership_subscriptions(id),
    CONSTRAINT fk_payments_enrollment   FOREIGN KEY (class_enrollment_id) REFERENCES class_enrollments(id),
    CONSTRAINT fk_payments_received_by  FOREIGN KEY (received_by) REFERENCES users(id)
);

CREATE INDEX ix_payments_member_status ON payments (member_id, status);
CREATE INDEX ix_payments_paid_at ON payments (paid_at);

CREATE TABLE invoices (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id          BIGINT NOT NULL UNIQUE,
    invoice_number      VARCHAR(50) NOT NULL UNIQUE,
    issued_at           TIMESTAMP NOT NULL,
    subtotal_amount     DECIMAL(12,2) NOT NULL,
    tax_amount          DECIMAL(12,2) NOT NULL DEFAULT 0,
    -- [FIX 1NF-3NF §3.6] total_amount là thuộc tính suy diễn từ subtotal_amount + tax_amount.
    -- Dùng COMPUTED COLUMN thay vì cột lưu tay để không bao giờ bị lệch dữ liệu.
    total_amount        GENERATED ALWAYS AS (subtotal_amount + tax_amount) STORED,
    pdf_url             VARCHAR(255) NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_invoices_payment FOREIGN KEY (payment_id) REFERENCES payments(id)
);

CREATE TABLE invoice_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id      BIGINT NOT NULL,
    description     VARCHAR(255) NOT NULL,
    quantity        INT NOT NULL DEFAULT 1,
    unit_price      DECIMAL(12,2) NOT NULL,
    -- [FIX 1NF-3NF §3.6] amount là thuộc tính suy diễn từ quantity * unit_price.
    amount          GENERATED ALWAYS AS (quantity * unit_price) STORED,
    CONSTRAINT fk_invoice_items_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
);

CREATE TABLE report_snapshots (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_type     VARCHAR(30) NOT NULL
                   CONSTRAINT ck_report_type CHECK (report_type IN ('revenue','membership','class_utilization')),
    period_start    DATE NOT NULL,
    period_end      DATE NOT NULL,
    data            JSONB NOT NULL,
    generated_by    BIGINT NULL,
    generated_at    TIMESTAMP NOT NULL,
    CONSTRAINT fk_reports_generated_by FOREIGN KEY (generated_by) REFERENCES users(id)
);

-- =====================================================================
-- MODULE G: HUẤN LUYỆN & ĐÁNH GIÁ
-- =====================================================================

CREATE TABLE training_plans (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id               BIGINT NOT NULL,
    coach_id                BIGINT NOT NULL,
    class_id                BIGINT NULL,
    goal                    VARCHAR(255) NULL,
    start_date              DATE NOT NULL,
    end_date                DATE NOT NULL,
    status                  VARCHAR(20) NOT NULL DEFAULT 'draft'
                           CONSTRAINT ck_plans_status CHECK (status IN ('draft','active','completed','cancelled')),
    is_ai_generated         BOOLEAN NOT NULL DEFAULT FALSE,
    ai_recommendation_id    BIGINT NULL, -- FK thêm bên dưới sau khi tạo ai_recommendation_logs
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_plans_member FOREIGN KEY (member_id) REFERENCES members(user_id),
    CONSTRAINT fk_plans_coach  FOREIGN KEY (coach_id) REFERENCES coaches(user_id),
    CONSTRAINT fk_plans_class  FOREIGN KEY (class_id) REFERENCES classes(id)
);

CREATE TABLE training_plan_items (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    training_plan_id    BIGINT NOT NULL,
    day_of_week         TINYINT NULL
                       CONSTRAINT ck_plan_items_day CHECK (day_of_week BETWEEN 1 AND 7),
    exercise_name       VARCHAR(150) NOT NULL,
    description         TEXT NULL,
    sets                INT NULL,
    reps                INT NULL,
    duration_minutes    INT NULL,
    order_index         INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_plan_items_plan FOREIGN KEY (training_plan_id) REFERENCES training_plans(id) ON DELETE CASCADE
);

CREATE TABLE session_evaluations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id          BIGINT NULL,
    member_id           BIGINT NOT NULL,
    coach_id            BIGINT NOT NULL,
    performance_notes   TEXT NULL,
    progress_score      DECIMAL(4,1) NULL,
    feedback            TEXT NULL,
    evaluated_at        TIMESTAMP NOT NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_eval_session FOREIGN KEY (session_id) REFERENCES class_sessions(id),
    CONSTRAINT fk_eval_member  FOREIGN KEY (member_id) REFERENCES members(user_id),
    CONSTRAINT fk_eval_coach   FOREIGN KEY (coach_id) REFERENCES coaches(user_id)
);

CREATE TABLE member_progress_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id       BIGINT NOT NULL,
    metric_name     VARCHAR(100) NOT NULL,
    metric_value    DECIMAL(10,2) NOT NULL,
    unit            VARCHAR(20) NULL,
    recorded_by     BIGINT NOT NULL,
    recorded_at     TIMESTAMP NOT NULL,
    CONSTRAINT fk_progress_member      FOREIGN KEY (member_id) REFERENCES members(user_id),
    CONSTRAINT fk_progress_recorded_by FOREIGN KEY (recorded_by) REFERENCES users(id)
);

-- =====================================================================
-- MODULE H: AI (OPTIONAL — FLOW 5 & FLOW 6)
-- =====================================================================

CREATE TABLE ai_recommendation_logs (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coach_id                BIGINT NULL,
    member_id               BIGINT NOT NULL,
    input_context           JSONB NOT NULL,
    recommended_content     JSONB NOT NULL,
    model_name              VARCHAR(100) NULL,
    is_applied              BOOLEAN NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_reco_coach  FOREIGN KEY (coach_id) REFERENCES coaches(user_id),
    CONSTRAINT fk_ai_reco_member FOREIGN KEY (member_id) REFERENCES members(user_id)
);

-- FK vòng: thêm sau khi ai_recommendation_logs đã tồn tại
ALTER TABLE training_plans
    ADD CONSTRAINT fk_plans_ai_recommendation
    FOREIGN KEY (ai_recommendation_id) REFERENCES ai_recommendation_logs(id);

CREATE TABLE ai_chat_sessions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id   BIGINT NOT NULL,
    topic       VARCHAR(150) NULL,
    started_at  TIMESTAMP NOT NULL,
    ended_at    TIMESTAMP NULL,
    CONSTRAINT fk_chat_sessions_member FOREIGN KEY (member_id) REFERENCES members(user_id)
);

CREATE TABLE ai_chat_messages (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT NOT NULL,
    sender      VARCHAR(10) NOT NULL
               CONSTRAINT ck_chat_sender CHECK (sender IN ('member','ai')),
    message     TEXT NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chat_messages_session FOREIGN KEY (session_id) REFERENCES ai_chat_sessions(id) ON DELETE CASCADE
);

-- =====================================================================
-- MODULE I: THÔNG BÁO & HỖ TRỢ
-- =====================================================================

CREATE TABLE notifications (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                 BIGINT NOT NULL,
    type                    VARCHAR(30) NOT NULL
                           CONSTRAINT ck_notifications_type CHECK (type IN ('schedule_change','package_expiry','class_reminder','system','support_reply','payment')),
    title                   VARCHAR(150) NOT NULL,
    message                 TEXT NOT NULL,
    is_read                 BOOLEAN NOT NULL DEFAULT FALSE,
    -- [FIX 1NF-3NF §3.8] FK đa hình: entity_id không có FOREIGN KEY thật vì có thể trỏ tới nhiều bảng.
    -- Bù lại bằng CHECK giới hạn danh sách bảng hợp lệ; entity_id phải được kiểm tra tồn tại ở tầng ứng dụng.
    related_entity_type     VARCHAR(50) NULL
                           CONSTRAINT ck_notifications_entity_type CHECK (
                               related_entity_type IS NULL OR related_entity_type IN (
                                   'class_session','membership_subscription','payment',
                                   'support_request','class_enrollment','training_plan'
                               )
                           ),
    related_entity_id       BIGINT NULL,
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX ix_notifications_user_read ON notifications (user_id, is_read);

CREATE TABLE support_requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id       BIGINT NOT NULL,
    assigned_to     BIGINT NULL,
    subject         VARCHAR(150) NOT NULL,
    description     TEXT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'open'
                   CONSTRAINT ck_support_status CHECK (status IN ('open','in_progress','resolved','closed')),
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    resolved_at     TIMESTAMP NULL,
    CONSTRAINT fk_support_member      FOREIGN KEY (member_id) REFERENCES members(user_id),
    CONSTRAINT fk_support_assigned_to FOREIGN KEY (assigned_to) REFERENCES users(id)
);

CREATE TABLE support_request_messages (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    support_request_id      BIGINT NOT NULL,
    sender_user_id          BIGINT NOT NULL,
    message                 TEXT NOT NULL,
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_support_msg_request FOREIGN KEY (support_request_id) REFERENCES support_requests(id) ON DELETE CASCADE,
    CONSTRAINT fk_support_msg_sender  FOREIGN KEY (sender_user_id) REFERENCES users(id)
);

-- =====================================================================
-- MODULE J: HỆ THỐNG
-- =====================================================================

CREATE TABLE audit_logs (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NULL,
    action          VARCHAR(100) NOT NULL,
    -- [FIX 1NF-3NF §3.8] FK đa hình tương tự notifications — giới hạn danh sách bảng được phép ghi log.
    entity_type     VARCHAR(100) NOT NULL
                   CONSTRAINT ck_audit_entity_type CHECK (entity_type IN (
                       'users','members','coaches','receptionists','center_managers',
                       'membership_packages','membership_subscriptions',
                       'classes','class_sessions','class_enrollments','class_waitlists',
                       'center_checkins','session_attendance',
                       'payments','invoices','invoice_items',
                       'training_plans','training_plan_items','session_evaluations',
                       'notifications','support_requests','role_permissions'
                   )),
    entity_id       BIGINT NULL,
    old_value       JSONB NULL,
    new_value       JSONB NULL,
    ip_address      VARCHAR(45) NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX ix_audit_entity ON audit_logs (entity_type, entity_id);
CREATE INDEX ix_audit_created_at ON audit_logs (created_at);

-- =====================================================================
-- DỮ LIỆU KHỞI TẠO (SEED DATA) — Roles cơ bản
-- =====================================================================

INSERT INTO roles (code, name, description) VALUES
('CENTER_MANAGER', 'Quản lý Trung tâm', 'Quản trị toàn bộ hệ thống, danh mục, báo cáo'),
('COACH', 'Huấn luyện viên', 'Phụ trách lớp học, đánh giá học viên'),
('MEMBER', 'Học viên / Thành viên', 'Người dùng cuối, đăng ký gói và lớp học'),
('RECEPTIONIST', 'Nhân viên Lễ tân', 'Xử lý đăng ký, thanh toán, check-in tại quầy');

-- =====================================================================
-- HẾT FILE
-- =====================================================================

