-- =====================================================================
-- MIGRATION V5: FINANCE MODULE (PAYMENTS, INVOICES & COMPUTED COLUMNS)
-- PostgreSQL 12+
-- =====================================================================

CREATE TABLE IF NOT EXISTS payments (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id               BIGINT NOT NULL,
    subscription_id         BIGINT NULL,
    class_enrollment_id     BIGINT NULL,
    amount                  NUMERIC(12,2) NOT NULL,
    method                  VARCHAR(20) NOT NULL
                            CONSTRAINT ck_payments_method CHECK (method IN ('cash','pos','bank_transfer','online_wallet')),
    status                  VARCHAR(20) NOT NULL DEFAULT 'pending'
                            CONSTRAINT ck_payments_status CHECK (status IN ('success','pending','failed','refunded')),
    paid_at                 TIMESTAMP NULL,
    received_by             BIGINT NULL,
    note                    VARCHAR(255) NULL,
    created_at              TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payments_member       FOREIGN KEY (member_id) REFERENCES members(user_id),
    CONSTRAINT fk_payments_subscription FOREIGN KEY (subscription_id) REFERENCES membership_subscriptions(id),
    CONSTRAINT fk_payments_enrollment   FOREIGN KEY (class_enrollment_id) REFERENCES class_enrollments(id),
    CONSTRAINT fk_payments_received_by  FOREIGN KEY (received_by) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS ix_payments_member_status ON payments (member_id, status);
CREATE INDEX IF NOT EXISTS ix_payments_paid_at ON payments (paid_at);

CREATE TABLE IF NOT EXISTS invoices (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id          BIGINT NOT NULL UNIQUE,
    invoice_number      VARCHAR(50) NOT NULL UNIQUE,
    issued_at           TIMESTAMP NOT NULL,
    subtotal_amount     NUMERIC(12,2) NOT NULL,
    tax_amount          NUMERIC(12,2) NOT NULL DEFAULT 0,
    -- [FIX 1NF-3NF §3.6] total_amount là thuộc tính suy diễn từ subtotal_amount + tax_amount.
    -- Dùng STORED generated column để đảm bảo tính toán đồng nhất ở tầng database.
    total_amount        NUMERIC(12,2) GENERATED ALWAYS AS (subtotal_amount + tax_amount) STORED,
    pdf_url             VARCHAR(255) NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_invoices_payment FOREIGN KEY (payment_id) REFERENCES payments(id)
);

CREATE TABLE IF NOT EXISTS invoice_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id      BIGINT NOT NULL,
    description     VARCHAR(255) NOT NULL,
    quantity        INT NOT NULL DEFAULT 1,
    unit_price      NUMERIC(12,2) NOT NULL,
    -- [FIX 1NF-3NF §3.6] amount là thuộc tính suy diễn từ quantity * unit_price.
    amount          NUMERIC(12,2) GENERATED ALWAYS AS (quantity * unit_price) STORED,
    CONSTRAINT fk_invoice_items_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
);
